language: java
jdk:
  - oraclejdk8

script:
  - ./gradlew test jacocoTestReport

after_success:
  - ./gradlew coveralls
  - if [[ "$TRAVIS_TAG" == *"v1."* ]]; then
      ./gradlew bintrayUpload;
    fi