language: java
jdk:
  - oraclejdk8

script:
  - ./gradlew test jacocoTestReport

after_success:
  - exit ./gradlew coveralls
  - if [[ "$TRAVIS_TAG" == *"v1."* ]]; then
      exit ./gradlew bintrayUpload;
    fi